# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_complain_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
