# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 11:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
    ]
