# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_room_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_amount',
            new_name='fees',
        ),
    ]
